name: Build and Test

on:
  push:
    branches: [master, ci-test]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 2 * * 0"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - container: 'ubuntu:22.04'
            test: 'yes'
          - container: 'ubuntu:24.04'
            test: 'yes'
          - container: 'archlinux:base-devel'
            test: 'yes'
          - container: 'fedora:latest'
            test: 'yes'
          - container: 'alpine:latest'
            test: 'no'
          - container: 'debian:unstable'
            test: 'yes'
            configure: '--disable-test-modules'

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ./.github/actions/setup-ubuntu
        if: ${{ startsWith(matrix.container, 'ubuntu') }}
      - uses: ./.github/actions/setup-archlinux
        if: ${{ startsWith(matrix.container, 'archlinux') }}
      - uses: ./.github/actions/setup-fedora
        if: ${{ startsWith(matrix.container, 'fedora') }}
      - uses: ./.github/actions/setup-alpine
        if: ${{ startsWith(matrix.container, 'alpine') }}
      - uses: ./.github/actions/setup-debian
        if: ${{ startsWith(matrix.container, 'debian') }}

      - name: configure
        run: |
          mkdir build
          cd build
          ../autogen.sh c ${{ matrix.configure }}

      - name: build
        run: |
          cd build
          make -j$(nproc)

      - name: test
        if: ${{ matrix.test == 'yes' }}
        run: |
          cd build
          make KDIR=/usr/lib/modules/*/build -j$(nproc) check

      - name: install
        run: |
          cd build
          DESTDIR=$PWD/inst make install

      - name: distcheck
        if: ${{ matrix.test == 'yes' }}
        run: |
          cd build
          DISTCHECK_CONFIGURE_FLAGS=${{ matrix.configure }} make KDIR=/usr/lib/modules/*/build distcheck
